version: "3"

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"          # Access frontend at localhost:80
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "4000:4000"      # Backend available at localhost:4000
